#!/usr/bin/env python

from gnuradio import analog
from gnuradio import eng_notation
from gnuradio import filter
from gnuradio import gr
from gnuradio.eng_option import eng_option
from gnuradio.filter import firdes
from optparse import OptionParser, OptionGroup
import igate
import osmosdr
import time

class aprs_dump(gr.top_block):
    def __init__(self, options):
        gr.top_block.__init__(self, "APRS dump")

        ##################################################
        # Variables
        ##################################################
        self.af_samp_rate = 9600
        self.if_samp_rate = self.af_samp_rate*2
        self.rf_samp_rate = self.if_samp_rate*48

        self.freq_offset = 100000
        self.freq = options.frequency

        self.channel_taps = firdes.low_pass(1, self.rf_samp_rate, 12500, 2000)

        ##################################################
        # Blocks
        ##################################################
        self.rf_src = osmosdr.source( args = options.args )
        self.rf_src.set_sample_rate( self.rf_samp_rate )
        self.rf_src.set_center_freq( self.freq+self.freq_offset, 0)
        self.rf_src.set_gain_mode(True, 0)
        self.rf_src.set_gain(34, 0)

        self.channel_filter = filter.freq_xlating_fft_filter_ccc(self.rf_samp_rate/self.if_samp_rate, self.channel_taps, -self.freq_offset, self.rf_samp_rate)

        # We don't care about gain, since we're going to FM-demodulate it again
        self.fm_demod = analog.quadrature_demod_cf(1.0)

        self.aprs_demod = igate.aprs_demod(self.if_samp_rate)

        self.dbg_print = igate.debug_print_msg()

        ##################################################
        # Connections
        ##################################################
        self.connect((self.rf_src, 0), (self.channel_filter, 0))
        self.connect((self.channel_filter, 0), (self.fm_demod, 0))
        self.connect((self.fm_demod, 0), (self.aprs_demod, 0))
        self.msg_connect((self.aprs_demod, 'out'), (self.dbg_print, 'in'))

def add_options(parser):
    group = OptionGroup(parser, "Receiver options")
    group.add_option("-f", "--frequency", type="eng_float", default=144.8e6,
                   help="Frequency of APRS channel [default=%default]")
    group.add_option("-a", "--args", type="string", default="",
                   help="Arguments for osmocom source block [default=%default]")

    parser.add_option_group(group)

if __name__ == '__main__':
    parser = OptionParser (option_class=eng_option, conflict_handler="resolve")
    add_options(parser)
    (options, args) = parser.parse_args ()

    tb = aprs_dump(options)
    tb.start()
    tb.wait()
